---
  - name: execute a local script on the host
    hosts: all
    become: false
    gather_facts: false
    tasks: 
      - name: copy file command
        ansible.builtin.command: sudo cp /scripts/host.sh /scripts/test/
      - name: execute script command
        ansible.builtin.command: sudo /scripts/test/host.sh
  
