---
  - name: execute a local script on the host
    hosts: all
    become: false
    gather_facts: false
    tasks: 
      - name: copy file command
        copy: src=/scripts/host.sh dest=/scripts/test
      - name: execute script command
        ansible.builtin.command: udo sh  /scripts/host.sh
  
